spring:
  application:
    name: springQuartzExample
  datasource:
    url: jdbc:hsqldb:mem:testdb
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
    username: sa
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.HSQLDialect
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always
  quartz:
    job-store-type: memory
    properties:
      org:
        quartz:
          scheduler:
            instanceName: quartzScheduler
          threadPool:
            threadCount: 3
          jobStore:
            class: org.quartz.simpl.RAMJobStore

logging:
  level:
    org:
      hibernate: debug
